---
label: siteconfig
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: title
- name: description
  type: text
  config:
    required: false
  label: description
